name: master
description: "Sem Papel"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # biblioteca para requsições.
  http: ^1.1.0

  # biblioteca para arquivos em http
  http_parser: ^4.0.2

  # biblioteca para requisições, para enviar o file.
  dio: ^5.3.3

  # biblioteca para rotas.
  get: ^4.6.6

  # biblioteca para abrir svg.
  flutter_svg: ^2.0.9

  # biblioteca para bordas pontilhadas.
  dotted_border: ^2.1.0

  # biblioteca para pegar arquivos
  file_picker: ^6.1.1

  # biblioteca para abrir site da web
  url_launcher: ^6.2.1

  # biblioteca para criar QrCode
  qr_flutter: ^4.0.0

  # biblioteca para ler QrCode
  qr_code_scanner: ^1.0.1
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Goldplay-black
      fonts:
        - asset: assets/fonts/Goldplay-Black.ttf
        
    - family: Goldplay-regular
      fonts:
        - asset: assets/fonts/Goldplay-Regular.ttf
