name: my_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  go_router: ^12.0.0
  flutter_svg: ^2.0.9
  dotted_border: ^2.1.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Goldplay-black
      fonts:
        - asset: assets/fonts/Goldplay-Black.ttf
        
    - family: Goldplay-regular
      fonts:
        - asset: assets/fonts/Goldplay-Regular.ttf
